### ISSUE TITLE
allowEmpty property is ignored

### ISSUE THREAD

**Issue by luisenriquegomesportugal** [ericblade/react-currency-input#38]
Regardless of whether I start the component with the allowEmpty property set to true or false, it always replaces the null value to 0.

In the documentation it says "If no value is given, defines if it starts as null (true) or '' (false)", however, it always starts as 0.

Initial Value:
`null`

Component: 
`<CurrencyInput
        prefix="R$ "
        allowEmpty={true}
        allowNegative={true}
        decimalSeparator=","
        thousandSeparator="." />`

I verified that the function that is executed when the value of the input changes even checks if this property is set to true or false, passing the null and the ''.
![image](https://github.com/ericblade/react-currency-input/assets/8116126/50147eaf-e655-43dd-9eba-f4bac10c811a)

however, the mask function is called, in this function the check is made if the value is true, if not, it returns 0, the interesting thing would be for it to remain empty.
![image](https://github.com/ericblade/react-currency-input/assets/8116126/8f53d249-b514-4ad4-b06a-5eb399ef9906)

I imagine the error is in this part of the code.
The correct thing would be that if the value was null, it would not show any value, but the placeholder of the field.

Could anyone help?

**Comment by ericblade** [comment]
seems entirely possible. I was just revamping the test structures here, and I didn't even remember implementing the allowEmpty, and I think tests for it were not there.  

Apologies for not seeing this in a timely fashion, I'll see what I can come up with though

**Comment by ericblade** [comment]
@luisenriquegomesportugal after converting the tests over to playwright, I discovered that the mask tests were not being run, and the mask tests were failing in a way that is quite probably relevant to this issue.

I'm correcting that, and issuing a 1.4.4 release.  Please let me know if that fixes this situation, and also if you'd like to contribute a test to ensure that this remains fixed, that'd be great, too

Thanks!

**Comment by ericblade** [comment]
btw, this automarked as closed because i referenced it in a pull request. please reopen if it's not
